DROP TABLE STAY CASCADE;
DROP TABLE VEHICLE CASCADE;
DROP TABLE PARKING CASCADE;
DROP TABLE CUSTOMER CASCADE;
DROP TABLE EMPLOYEE CASCADE;
DROP TABLE NATURAL_PERSON CASCADE;
DROP TABLE LEGAL_ENTITY CASCADE;
DROP TABLE PERSON CASCADE;
DROP TABLE PRICE_TABLE CASCADE;
DROP TABLE VEHICLE_TYPE CASCADE;

CREATE TABLE VEHICLE_TYPE(
	MANUFACTURER VARCHAR(50) NULL, 
	MODEL VARCHAR(20) NULL, 
	VTYPE VARCHAR(20) NOT NULL, 
	PRIMARY KEY (VTYPE));

CREATE TABLE PRICE_TABLE (
	CD_PRICE_TABLE INTEGER NOT NULL, 
	ITEM VARCHAR(50) NOT NULL, 
	PRICE DECIMAL NOT NULL, 
	PRIMARY KEY (CD_PRICE_TABLE));


CREATE TABLE PERSON (
	CD_PERSON INTEGER NOT NULL, 
	ADDRESS VARCHAR(100) NULL, 
	NAME VARCHAR(100) NOT NULL, 
	DTYPE CHARACTER(2) NOT NULL,
	VERSION INTEGER NULL,
	PRIMARY KEY(CD_PERSON));

CREATE TABLE LEGAL_ENTITY (
	CD_PERSON INTEGER NOT NULL, 
	TAXPAYERS_ID VARCHAR(20) NOT NULL, 
	DT_FOUNDATION DATE NOT NULL, 
	PRIMARY KEY (CD_PERSON));

CREATE TABLE NATURAL_PERSON (
	CD_PERSON INTEGER NOT NULL, 
	DT_BIRTH DATE NULL, 
	RG VARCHAR(20) NULL, 
	PRIMARY KEY (CD_PERSON));

CREATE TABLE EMPLOYEE (
	CD_EMPLOYEE INTEGER NOT NULL, /* CD_PERSON INTEGER NOT NULL,*/ 
	DT_ADMISSION DATE NOT NULL, 
	CD_PARKING INTEGER NOT NULL,	
	USERNAME VARCHAR(20) NULL,
	PASSWORD VARCHAR(20) NULL,	
	PRIMARY KEY (CD_EMPLOYEE));

CREATE TABLE CUSTOMER (
	CD_CUSTOMER INTEGER NOT NULL, /* CD_PERSON INTEGER NOT NULL,*/
	PAYMENT_DAY INTEGER NULL,
	PRIMARY KEY (CD_CUSTOMER));

	
CREATE TABLE PARKING (
	CD_PARKING INTEGER NOT NULL, 
	ADDRESS VARCHAR(100) NOT NULL, 
	PARKING_SPACES INTEGER NULL,
	PRIMARY KEY (CD_PARKING));

CREATE TABLE STAY (
	CD_STAY INTEGER NOT NULL,
	CD_PARKING INTEGER NOT NULL, 
	DT_ENTRANCE DATE NOT NULL, 
	DT_OUTGOING DATE NULL, 
	HR_ENTRANCE TIME NOT NULL, 
	HR_OUTGOING TIME NULL,
	CD_EMPLOYEE_ENTRANCE INTEGER NOT NULL, 
	CD_EMPLOYEE_OUTGOING INTEGER NOT NULL,
	LICENSE_PLATE VARCHAR(20) NOT NULL, 
	STATUS SMALLINT NULL, 
	PRICE DECIMAL NULL, PRIMARY KEY (CD_STAY));

CREATE TABLE VEHICLE (
	LICENSE_PLATE VARCHAR(20) NOT NULL, 
	VTYPE VARCHAR(20) NOT NULL, 
	CD_CUSTOMER INTEGER NOT NULL, 
	CD_PRICE_TABLE INTEGER NOT NULL, 
	COLOR VARCHAR(20) NULL, 
	PRIMARY KEY (LICENSE_PLATE));
