--Needs to be first
DELETE FROM VEHICLE;
DELETE FROM VEHICLE_TYPE;
DELETE FROM PRICE_TABLE;

--Now it will work
DELETE FROM CUSTOMER;
DELETE FROM NATURAL_PERSON;
DELETE FROM LEGAL_ENTITY;
DELETE FROM PERSON;

--PERSON TABLE;
INSERT INTO PERSON (ID_PERSON, ADDRESS,	NAME, P_TYPE)	VALUES(1,'ADDRESS1','LEGAL_ENTITY','LE');
INSERT INTO PERSON (ID_PERSON, ADDRESS,	NAME, P_TYPE)	VALUES(2,'ADDRESS2','NATURAL_PERSON','NP');
--LEGAL_ENTITY TABLE
INSERT INTO LEGAL_ENTITY (ID_PERSON,TAXPAYERS_ID, DT_FOUNDATION)	VALUES(1,'1212','2009-03-21');
--NATURAL_PERSON TABLE
INSERT INTO NATURAL_PERSON (ID_PERSON, DT_BIRTH, RG)	VALUES(2,'2009-03-21', '19552 SSP');
--CUSTOMER TABLE
INSERT INTO CUSTOMER (CD_CUSTOMER, PAYMENT_DAY)	VALUES(2, 2);


--VEHICLE
INSERT INTO PRICE_TABLE(CD_PRICE_TABLE, ITEM, PRICE) VALUES(1, 'CARRO',2.00);
--VEHICLE_TYPE
INSERT INTO VEHICLE_TYPE(V_TYPE, MANUFACTURER, MODEL) VALUES('CARRO', 'FIAT','UNO');
--PRICE_TABLE
INSERT INTO VEHICLE(CD_CUSTOMER, CD_PRICE_TABLE, COLOR, LICENSE_PLATE,V_TYPE) VALUES(2, 1, 'COR', 'PLACA','CARRO');
