-- Role: "park"

-- DROP ROLE park;

CREATE ROLE park LOGIN
  ENCRYPTED PASSWORD 'md5cc67fcf394136f13be5b9615a8ff6310'
  NOSUPERUSER NOINHERIT CREATEDB CREATEROLE;
  
-- Schema: "park"

-- DROP SCHEMA park;

CREATE SCHEMA park
  AUTHORIZATION park;
GRANT ALL ON SCHEMA park TO park;

--DROP DOMAIN BOOLEAN;
--CREATE DOMAIN BOOLEAN AS VARCHAR(1) DEFAULT '0' CHECK (VALUE IN ('S','s', 'N','n','0','1'));

