DROP TABLE STAY CASCADE;
DROP TABLE VEHICLE CASCADE;
DROP TABLE PARKING CASCADE;
DROP TABLE CUSTOMER CASCADE;
DROP TABLE EMPLOYEE CASCADE;
DROP TABLE NATURAL_PERSON CASCADE;
DROP TABLE LEGAL_ENTITY CASCADE;
DROP TABLE PERSON CASCADE;
DROP TABLE PRICE_TABLE CASCADE;
DROP TABLE VEHICLE_TYPE CASCADE;


CREATE TABLE VEHICLE_TYPE (
                V_TYPE VARCHAR(20) NOT NULL,
                MANUFACTURER VARCHAR(50),
                MODEL VARCHAR(20),
                CONSTRAINT vehicle_type_pk PRIMARY KEY (V_TYPE)
);


CREATE UNIQUE INDEX primary_key_1
 ON VEHICLE_TYPE
 ( V_TYPE );

CREATE TABLE PERSON (
                ID_PERSON INTEGER NOT NULL,
                ADDRESS VARCHAR(100),
                NAME VARCHAR(100) NOT NULL,
                P_TYPE CHAR(2) NOT NULL,
                VERSION SMALLINT NOT NULL,
                CONSTRAINT person_pk PRIMARY KEY (ID_PERSON)
);


CREATE UNIQUE INDEX primary_key_8
 ON PERSON
 ( ID_PERSON );

CREATE TABLE LEGAL_ENTITY (
                ID_PERSON INTEGER NOT NULL,
                TAXPAYERS_ID VARCHAR(20) NOT NULL,
                DT_FOUNDATION DATE NOT NULL,
                CONSTRAINT LEGAL_ENTITY_PK PRIMARY KEY (ID_PERSON)
);


CREATE UNIQUE INDEX primary_key_c
 ON LEGAL_ENTITY
 ( ID_PERSON );

CREATE TABLE NATURAL_PERSON (
                ID_PERSON INTEGER NOT NULL,
                DT_BIRTH DATE,
                LEGAL_DOCUMENT VARCHAR(20),
                CONSTRAINT natural_person_pk PRIMARY KEY (ID_PERSON)
);


CREATE UNIQUE INDEX primary_key_4
 ON NATURAL_PERSON
 ( ID_PERSON );

CREATE TABLE PARKING (
                ID_PARKING INTEGER NOT NULL,
                ID_PERSON INTEGER NOT NULL,
                PARKING_SPACES INTEGER,
                CONSTRAINT parking_pk PRIMARY KEY (ID_PARKING)
);


CREATE UNIQUE INDEX parking_idx
 ON PARKING
 ( ID_PARKING, ID_PERSON );

CREATE UNIQUE INDEX primary_key_f
 ON PARKING
 ( ID_PARKING );

CREATE INDEX parking_id_person_fk_index_f
 ON PARKING
 ( ID_PERSON );

CREATE TABLE CUSTOMER (
                ID_CUSTOMER INTEGER NOT NULL,
                ID_PERSON INTEGER NOT NULL,
                PAYMENT_DAY INTEGER,
                CONSTRAINT customer_pk PRIMARY KEY (ID_CUSTOMER)
);


CREATE UNIQUE INDEX customer_idx
 ON CUSTOMER
 ( ID_PERSON );

CREATE UNIQUE INDEX primary_key_5
 ON CUSTOMER
 ( ID_CUSTOMER );

CREATE TABLE EMPLOYEE (
                ID_EMPLOYEE INTEGER NOT NULL,
                ID_PERSON INTEGER NOT NULL,
                DT_ADMISSION DATE NOT NULL,
                ID_PARKING INTEGER NOT NULL,
                CONSTRAINT employee_pk PRIMARY KEY (ID_EMPLOYEE)
);


CREATE UNIQUE INDEX employee_idx
 ON EMPLOYEE
 ( ID_PERSON );

CREATE UNIQUE INDEX primary_key_7
 ON EMPLOYEE
 ( ID_EMPLOYEE );

CREATE INDEX parking_id_employee_fkey_index_7
 ON EMPLOYEE
 ( ID_PARKING );

CREATE TABLE PRICE_TABLE (
                ID_PRICE_TABLE INTEGER NOT NULL,
                ITEM VARCHAR(50) NOT NULL,
                PRICE NUMERIC(12,2) NOT NULL,
                CONSTRAINT price_table_pk PRIMARY KEY (ID_PRICE_TABLE)
);


CREATE UNIQUE INDEX primary_key_2
 ON PRICE_TABLE
 ( ID_PRICE_TABLE );

CREATE TABLE VEHICLE (
                LICENSE_PLATE VARCHAR(20) NOT NULL,
                V_TYPE VARCHAR(20) NOT NULL,
                ID_CUSTOMER INTEGER NOT NULL,
                ID_PRICE_TABLE INTEGER NOT NULL,
                COLOR VARCHAR(20),
                CONSTRAINT vehicle_pk PRIMARY KEY (LICENSE_PLATE)
);


CREATE UNIQUE INDEX primary_key_3
 ON VEHICLE
 ( LICENSE_PLATE );

CREATE INDEX vehicle_id_customer_fkey_index_3
 ON VEHICLE
 ( ID_CUSTOMER );

CREATE INDEX vehicle_id_price_table_fkey_index_3
 ON VEHICLE
 ( ID_PRICE_TABLE );

CREATE INDEX vehicle_v_type_fkey_index_3
 ON VEHICLE
 ( V_TYPE );

CREATE TABLE STAY (
                ID_STAY INTEGER NOT NULL,
                ID_PARKING INTEGER NOT NULL,
                DT_ENTRANCE DATE NOT NULL,
                DT_OUTGOING DATE,
                HR_ENTRANCE TIME NOT NULL,
                HR_OUTGOING TIME,
                ID_EMPLOYEE_ENTRANCE INTEGER NOT NULL,
                ID_EMPLOYEE_OUTGOING INTEGER NOT NULL,
                LICENSE_PLATE VARCHAR(20) NOT NULL,
                STATUS CHAR(1),
                PRICE NUMERIC(12,2),
                CONSTRAINT stay_pk PRIMARY KEY (ID_STAY)
);


CREATE UNIQUE INDEX primary_key_26
 ON STAY
 ( ID_STAY );

CREATE UNIQUE INDEX stay_idx
 ON STAY
 ( ID_STAY, ID_PARKING, DT_ENTRANCE, HR_ENTRANCE, ID_EMPLOYEE_ENTRANCE, LICENSE_PLATE );

CREATE INDEX stay_id_employee_entrance_fkey_index_2
 ON STAY
 ( ID_EMPLOYEE_ENTRANCE );

CREATE INDEX stay_id_employee_outgoing_fkey_index_2
 ON STAY
 ( ID_EMPLOYEE_OUTGOING );

CREATE INDEX stay_id_parking_fkey_index_2
 ON STAY
 ( ID_PARKING );

CREATE INDEX stay_license_plate_fkey_index_2
 ON STAY
 ( LICENSE_PLATE );

ALTER TABLE VEHICLE ADD CONSTRAINT vehicle_v_type_fkey
FOREIGN KEY (V_TYPE)
REFERENCES VEHICLE_TYPE (V_TYPE)
ON DELETE RESTRICT
ON UPDATE RESTRICT
NOT DEFERRABLE;

ALTER TABLE CUSTOMER ADD CONSTRAINT customer_id_person_fk
FOREIGN KEY (ID_PERSON)
REFERENCES PERSON (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
NOT DEFERRABLE;

ALTER TABLE NATURAL_PERSON ADD CONSTRAINT naturalperson_id_person_fkey
FOREIGN KEY (ID_PERSON)
REFERENCES PERSON (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
NOT DEFERRABLE;

ALTER TABLE LEGAL_ENTITY ADD CONSTRAINT legalentity_id_person_fkey
FOREIGN KEY (ID_PERSON)
REFERENCES PERSON (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
NOT DEFERRABLE;

ALTER TABLE PARKING ADD CONSTRAINT parking_id_person_fk
FOREIGN KEY (ID_PERSON)
REFERENCES LEGAL_ENTITY (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
NOT DEFERRABLE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT employee_id_person_fk
FOREIGN KEY (ID_PERSON)
REFERENCES NATURAL_PERSON (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
NOT DEFERRABLE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT parking_id_employee_fkey
FOREIGN KEY (ID_PARKING)
REFERENCES PARKING (ID_PARKING)
ON DELETE RESTRICT
ON UPDATE RESTRICT
NOT DEFERRABLE;

ALTER TABLE STAY ADD CONSTRAINT stay_id_parking_fkey
FOREIGN KEY (ID_PARKING)
REFERENCES PARKING (ID_PARKING)
ON DELETE CASCADE
ON UPDATE CASCADE
NOT DEFERRABLE;

ALTER TABLE VEHICLE ADD CONSTRAINT vehicle_id_customer_fkey
FOREIGN KEY (ID_CUSTOMER)
REFERENCES CUSTOMER (ID_CUSTOMER)
ON DELETE RESTRICT
ON UPDATE RESTRICT
NOT DEFERRABLE;

ALTER TABLE STAY ADD CONSTRAINT stay_id_employee_entrance_fkey
FOREIGN KEY (ID_EMPLOYEE_ENTRANCE)
REFERENCES EMPLOYEE (ID_EMPLOYEE)
ON DELETE RESTRICT
ON UPDATE RESTRICT
NOT DEFERRABLE;

ALTER TABLE STAY ADD CONSTRAINT stay_id_employee_outgoing_fkey
FOREIGN KEY (ID_EMPLOYEE_OUTGOING)
REFERENCES EMPLOYEE (ID_EMPLOYEE)
ON DELETE RESTRICT
ON UPDATE RESTRICT
NOT DEFERRABLE;

ALTER TABLE VEHICLE ADD CONSTRAINT vehicle_id_price_table_fkey
FOREIGN KEY (ID_PRICE_TABLE)
REFERENCES PRICE_TABLE (ID_PRICE_TABLE)
ON DELETE RESTRICT
ON UPDATE RESTRICT
NOT DEFERRABLE;

ALTER TABLE STAY ADD CONSTRAINT stay_license_plate_fkey
FOREIGN KEY (LICENSE_PLATE)
REFERENCES VEHICLE (LICENSE_PLATE)
ON DELETE RESTRICT
ON UPDATE RESTRICT
NOT DEFERRABLE;