DROP TABLE STAY CASCADE;
DROP TABLE VEHICLE CASCADE;
DROP TABLE PARKING CASCADE;
DROP TABLE CUSTOMER CASCADE;
DROP TABLE EMPLOYEE CASCADE;
DROP TABLE NATURAL_PERSON CASCADE;
DROP TABLE LEGAL_ENTITY CASCADE;
DROP TABLE PERSON CASCADE;
DROP TABLE PRICE_TABLE CASCADE;
DROP TABLE VEHICLE_TYPE CASCADE;

CREATE TABLE VEHICLE_TYPE (
                V_TYPE VARCHAR(20) NOT NULL,
                MANUFACTURER VARCHAR(50),
                MODEL VARCHAR(20),
                CONSTRAINT VEHICLE_V_TYPE_PKEY PRIMARY KEY (V_TYPE)
);


CREATE TABLE PRICE_TABLE (
                ID_PRICE_TABLE INTEGER NOT NULL,
                ITEM VARCHAR(50) NOT NULL,
                PRICE DECIMAL(12,2) NOT NULL,
                CONSTRAINT PRICE_TABLE_PKEY PRIMARY KEY (ID_PRICE_TABLE)
);


CREATE TABLE PERSON (
                ID_PERSON INTEGER NOT NULL,
                ADDRESS VARCHAR(100),
                NAME VARCHAR(100) NOT NULL,
                P_TYPE CHAR(2) NOT NULL,
                VERSION SMALLINT NOT NULL,
                CONSTRAINT PERSON_PKEY PRIMARY KEY (ID_PERSON)
);


CREATE TABLE NATURAL_PERSON (
                ID_PERSON INTEGER NOT NULL,
                DT_BIRTH DATE,
                LEGAL_DOCUMENT VARCHAR(20),
                CONSTRAINT NATURAL_PERSON_PKEY PRIMARY KEY (ID_PERSON)
);


CREATE TABLE LEGAL_ENTITY (
                ID_PERSON INTEGER NOT NULL,
                TAXPAYERS_ID VARCHAR(20) NOT NULL,
                DT_FOUNDATION DATE NOT NULL,
                CONSTRAINT LEGAL_ENTITY_PKEY PRIMARY KEY (ID_PERSON)
);


CREATE TABLE PARKING (
                ID_PARKING INTEGER NOT NULL,
                ID_PERSON INTEGER NOT NULL,
                PARKING_SPACES INTEGER,
                CONSTRAINT PARKING_PKEY PRIMARY KEY (ID_PARKING)
);


CREATE UNIQUE INDEX PARKING_IDX
 ON PARKING
 ( ID_PARKING, ID_PERSON );

CREATE TABLE EMPLOYEE (
                ID_EMPLOYEE INTEGER NOT NULL,
                ID_PERSON INTEGER NOT NULL,
                DT_ADMISSION DATE NOT NULL,
                ID_PARKING INTEGER NOT NULL,
                CONSTRAINT EMPLOYEE_PKEY PRIMARY KEY (ID_EMPLOYEE)
);


CREATE UNIQUE INDEX EMPLOYEE_IDX
 ON EMPLOYEE
 ( ID_PERSON );

CREATE TABLE CUSTOMER (
                ID_CUSTOMER INTEGER NOT NULL,
                ID_PERSON INTEGER NOT NULL,
                PAYMENT_DAY INTEGER,
                CONSTRAINT CUSTOMER_PKEY PRIMARY KEY (ID_CUSTOMER)
);


CREATE UNIQUE INDEX CUSTOMER_IDX
 ON CUSTOMER
 ( ID_PERSON );

CREATE TABLE VEHICLE (
                LICENSE_PLATE VARCHAR(20) NOT NULL,
                V_TYPE VARCHAR(20) NOT NULL,
                ID_CUSTOMER INTEGER NOT NULL,
                ID_PRICE_TABLE INTEGER NOT NULL,
                COLOR VARCHAR(20),
                CONSTRAINT VEHICLE_PKEY PRIMARY KEY (LICENSE_PLATE)
);


CREATE TABLE STAY (
                ID_STAY INTEGER NOT NULL,
                ID_PARKING INTEGER NOT NULL,
                DT_ENTRANCE DATE NOT NULL,
                DT_OUTGOING DATE,
                HR_ENTRANCE TIME NOT NULL,
                HR_OUTGOING TIME,
                ID_EMPLOYEE_ENTRANCE INTEGER NOT NULL,
                ID_EMPLOYEE_OUTGOING INTEGER NOT NULL,
                LICENSE_PLATE VARCHAR(20) NOT NULL,
                STATUS SMALLINT,
                PRICE DECIMAL(12,2),
                CONSTRAINT STAY_PKEY PRIMARY KEY (ID_STAY)
);


CREATE UNIQUE INDEX STAY_IDX
 ON STAY
 ( ID_STAY, ID_PARKING, DT_ENTRANCE, HR_ENTRANCE, ID_EMPLOYEE_ENTRANCE, LICENSE_PLATE );

ALTER TABLE VEHICLE ADD CONSTRAINT VEHICLE_V_TYPE_FKEY
FOREIGN KEY (V_TYPE)
REFERENCES VEHICLE_TYPE (V_TYPE)
ON DELETE RESTRICT
ON UPDATE RESTRICT
;

ALTER TABLE VEHICLE ADD CONSTRAINT VEHICLE_ID_PRICE_TABLE_FKEY
FOREIGN KEY (ID_PRICE_TABLE)
REFERENCES PRICE_TABLE (ID_PRICE_TABLE)
ON DELETE RESTRICT
ON UPDATE RESTRICT
;

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_ID_PERSON_FK
FOREIGN KEY (ID_PERSON)
REFERENCES PERSON (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE LEGAL_ENTITY ADD CONSTRAINT LEGALENTITY_ID_PERSON_FKEY
FOREIGN KEY (ID_PERSON)
REFERENCES PERSON (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE NATURAL_PERSON ADD CONSTRAINT NATURALPERSON_ID_PERSON_FKEY
FOREIGN KEY (ID_PERSON)
REFERENCES PERSON (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_ID_PERSON_FK
FOREIGN KEY (ID_PERSON)
REFERENCES NATURAL_PERSON (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE PARKING ADD CONSTRAINT PARKING_ID_PERSON_FK
FOREIGN KEY (ID_PERSON)
REFERENCES LEGAL_ENTITY (ID_PERSON)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE EMPLOYEE ADD CONSTRAINT PARKING_ID_EMPLOYEE_FKEY
FOREIGN KEY (ID_PARKING)
REFERENCES PARKING (ID_PARKING)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;

ALTER TABLE STAY ADD CONSTRAINT STAY_ID_PARKING_FKEY
FOREIGN KEY (ID_PARKING)
REFERENCES PARKING (ID_PARKING)
ON DELETE CASCADE
ON UPDATE CASCADE
;

ALTER TABLE STAY ADD CONSTRAINT STAY_ID_EMPLOYEE_OUTGOING_FKEY
FOREIGN KEY (ID_EMPLOYEE_OUTGOING)
REFERENCES EMPLOYEE (ID_EMPLOYEE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;

ALTER TABLE STAY ADD CONSTRAINT STAY_ID_EMPLOYEE_ENTRANCE_FKEY
FOREIGN KEY (ID_EMPLOYEE_ENTRANCE)
REFERENCES EMPLOYEE (ID_EMPLOYEE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;

ALTER TABLE VEHICLE ADD CONSTRAINT VEHICLE_ID_CUSTOMER_FKEY
FOREIGN KEY (ID_CUSTOMER)
REFERENCES CUSTOMER (ID_CUSTOMER)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;

ALTER TABLE STAY ADD CONSTRAINT STAY_LICENSE_PLATE_FKEY
FOREIGN KEY (LICENSE_PLATE)
REFERENCES VEHICLE (LICENSE_PLATE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;