ALTER TABLE STAY
ADD CONSTRAINT STAY_CHECK_STATUS CHECK (STATUS IN (1,2,3));
--1: VEHICLE IN
--2: VEHICLE OUT
--3: CANCELED

CREATE UNIQUE INDEX STAY_CD_PARKING_KEY
 ON STAY( CD_PARKING, DT_ENTRANCE, CD_EMPLOYEE_ENTRANCE, LICENSE_PLATE );

ALTER TABLE VEHICLE ADD CONSTRAINT VEHICLE_TYPE_FKEY
FOREIGN KEY (VTYPE)
REFERENCES VEHICLE_TYPE (VTYPE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE VEHICLE ADD CONSTRAINT VEHICLE_CD_PRICE_TABLE_FKEY
FOREIGN KEY (CD_PRICE_TABLE)
REFERENCES PRICE_TABLE (CD_PRICE_TABLE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_CD_CUSTOMER_FKEY
FOREIGN KEY (CD_CUSTOMER)
REFERENCES PERSON (CD_PERSON)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE LEGAL_ENTITY ADD CONSTRAINT LEGALENTITY_CD_PERSON_FKEY
FOREIGN KEY (CD_PERSON)
REFERENCES PERSON (CD_PERSON)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE NATURAL_PERSON ADD CONSTRAINT NATURALPERSON_CD_PERSON_FKEY
FOREIGN KEY (CD_PERSON)
REFERENCES PERSON (CD_PERSON)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_CD_PARKING_FKEY
FOREIGN KEY (CD_PARKING)
REFERENCES PARKING (CD_PARKING)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE STAY ADD CONSTRAINT STAY_CD_PARKING_FKEY
FOREIGN KEY (CD_PARKING)
REFERENCES PARKING (CD_PARKING)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_CD_EMPLOYEE_FKEY
FOREIGN KEY (CD_EMPLOYEE)
REFERENCES NATURAL_PERSON (CD_PERSON)
ON DELETE CASCADE
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE STAY ADD CONSTRAINT STAY_CD_EMPLOYEE_OUTGOING_FKEY
FOREIGN KEY (CD_EMPLOYEE_OUTGOING)
REFERENCES EMPLOYEE (CD_EMPLOYEE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE STAY ADD CONSTRAINT STAY_CD_EMPLOYEE_ENTRANCE_FKEY
FOREIGN KEY (CD_EMPLOYEE_ENTRANCE)
REFERENCES EMPLOYEE (CD_EMPLOYEE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE VEHICLE ADD CONSTRAINT VEHICLE_CD_CUSTOMER_FKEY
FOREIGN KEY (CD_CUSTOMER)
REFERENCES CUSTOMER (CD_CUSTOMER)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE STAY ADD CONSTRAINT STAY_LICENSE_PLATE_FKEY
FOREIGN KEY (LICENSE_PLATE)
REFERENCES VEHICLE (LICENSE_PLATE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;