package com.google.constructor.cip.security.cayenne.domain.auto;

import org.apache.cayenne.CayenneDataObject;

import com.google.constructor.cip.security.cayenne.domain.Role;

/**
 * Class _RolePermission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RolePermission extends CayenneDataObject {

    public static final String PERMISSION_PROPERTY = "permission";
    public static final String ROLE_ID_PROPERTY = "roleId";
    public static final String ROLE_PROPERTY = "role";

    public static final String PERMISSION_PK_COLUMN = "PERMISSION";
    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public void setPermission(String permission) {
        writeProperty("permission", permission);
    }
    public String getPermission() {
        return (String)readProperty("permission");
    }

    public void setRoleId(Long roleId) {
        writeProperty("roleId", roleId);
    }
    public Long getRoleId() {
        return (Long)readProperty("roleId");
    }

    public void setRole(Role role) {
        setToOneTarget("role", role, true);
    }

    public Role getRole() {
        return (Role)readProperty("role");
    }


}
