package com.google.constructor.extras.security.cayenne.domain.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.google.constructor.extras.security.cayenne.domain.Role;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String ID_PROPERTY = "id";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String USERNAME_PROPERTY = "username";
    public static final String VERSION_PROPERTY = "version";
    public static final String ROLES_PROPERTY = "roles";

    public static final String ID_PK_COLUMN = "ID";

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setId(Long id) {
        writeProperty("id", id);
    }
    public Long getId() {
        return (Long)readProperty("id");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }

    public void setVersion(Integer version) {
        writeProperty("version", version);
    }
    public Integer getVersion() {
        return (Integer)readProperty("version");
    }

    public void addToRoles(Role obj) {
        addToManyTarget("roles", obj, true);
    }
    public void removeFromRoles(Role obj) {
        removeToManyTarget("roles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Role> getRoles() {
        return (List<Role>)readProperty("roles");
    }


}
