CREATE TABLE FINANCEIRO.MOVIMENTO_CAIXA (
    CD_MOVIMENTO_CAIXA INTEGER NOT NULL,
    FL_PROCESSADO SMALLINT,
    DT_HR_MOVIMENTO TIMESTAMP,
    DT_HR_ABERTURA TIMESTAMP,
    FL_FECHADO SMALLINT,
    ENTRADAS DECIMAL(5, 2),
    SAIDAS DECIMAL(5, 2),
    SALDO_ANTERIOR DECIMAL(5, 2),
    SALDO DECIMAL(5, 2),
    CD_FUNCIONARIO INTEGER,
    CD_CAIXA INTEGER,
    PRIMARY KEY (CD_MOVIMENTO_CAIXA)
);
