package park.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import park.model.NaturalPerson;
import park.model.Parking;
import park.model.Stay;

/**
 * Class _Employee was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Employee extends CayenneDataObject {

    public static final String DT_ADMISSION_PROPERTY = "dtAdmission";
    public static final String ENTRANCE_STAYS_PROPERTY = "entranceStays";
    public static final String OUTGOING_STAYS_PROPERTY = "outgoingStays";
    public static final String TO_NATURAL_PERSON_PROPERTY = "toNaturalPerson";
    public static final String TO_PARKING_PROPERTY = "toParking";

    public static final String ID_PK_COLUMN = "ID";

    public void setDtAdmission(Date dtAdmission) {
        writeProperty("dtAdmission", dtAdmission);
    }
    public Date getDtAdmission() {
        return (Date)readProperty("dtAdmission");
    }

    public void addToEntranceStays(Stay obj) {
        addToManyTarget("entranceStays", obj, true);
    }
    public void removeFromEntranceStays(Stay obj) {
        removeToManyTarget("entranceStays", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Stay> getEntranceStays() {
        return (List<Stay>)readProperty("entranceStays");
    }


    public void addToOutgoingStays(Stay obj) {
        addToManyTarget("outgoingStays", obj, true);
    }
    public void removeFromOutgoingStays(Stay obj) {
        removeToManyTarget("outgoingStays", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Stay> getOutgoingStays() {
        return (List<Stay>)readProperty("outgoingStays");
    }



    public NaturalPerson getToNaturalPerson() {
        return (NaturalPerson)readProperty("toNaturalPerson");
    }


    public void setToParking(Parking toParking) {
        setToOneTarget("toParking", toParking, true);
    }

    public Parking getToParking() {
        return (Parking)readProperty("toParking");
    }


}
