package park.model.auto;

import java.util.Date;

import park.model.Customer;
import park.model.Parking;

/**
 * Class _LegalEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LegalEntity extends Parking {

    public static final String DT_FOUNDATION_PROPERTY = "dtFoundation";
    public static final String NAME_PROPERTY = "name";
    public static final String P_TYPE_PROPERTY = "pType";
    public static final String TAXPAYERS_ID_PROPERTY = "taxpayersId";
    public static final String VERSION_PROPERTY = "version";
    public static final String TO_CUSTOMER_PROPERTY = "toCustomer";

    public static final String ID_PK_COLUMN = "ID";

    public void setDtFoundation(Date dtFoundation) {
        writeProperty("dtFoundation", dtFoundation);
    }
    public Date getDtFoundation() {
        return (Date)readProperty("dtFoundation");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPType(String pType) {
        writeProperty("pType", pType);
    }
    public String getPType() {
        return (String)readProperty("pType");
    }

    public void setTaxpayersId(String taxpayersId) {
        writeProperty("taxpayersId", taxpayersId);
    }
    public String getTaxpayersId() {
        return (String)readProperty("taxpayersId");
    }

    public void setVersion(Integer version) {
        writeProperty("version", version);
    }
    public Integer getVersion() {
        return (Integer)readProperty("version");
    }

    public void setToCustomer(Customer toCustomer) {
        setToOneTarget("toCustomer", toCustomer, true);
    }

    public Customer getToCustomer() {
        return (Customer)readProperty("toCustomer");
    }


}
