package park.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import park.model.Employee;
import park.model.Stay;

/**
 * Class _Parking was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Parking extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String ID_PROPERTY = "id";
    public static final String PARKING_SPACE_PROPERTY = "parkingSpace";
    public static final String EMPLOYEES_PROPERTY = "employees";
    public static final String STAYS_PROPERTY = "stays";

    public static final String ID_PK_COLUMN = "ID";

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setId(Long id) {
        writeProperty("id", id);
    }
    public Long getId() {
        return (Long)readProperty("id");
    }

    public void setParkingSpace(Integer parkingSpace) {
        writeProperty("parkingSpace", parkingSpace);
    }
    public Integer getParkingSpace() {
        return (Integer)readProperty("parkingSpace");
    }

    public void addToEmployees(Employee obj) {
        addToManyTarget("employees", obj, true);
    }
    public void removeFromEmployees(Employee obj) {
        removeToManyTarget("employees", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Employee> getEmployees() {
        return (List<Employee>)readProperty("employees");
    }


    public void addToStays(Stay obj) {
        addToManyTarget("stays", obj, true);
    }
    public void removeFromStays(Stay obj) {
        removeToManyTarget("stays", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Stay> getStays() {
        return (List<Stay>)readProperty("stays");
    }


}
