package park.model.auto;

import org.apache.cayenne.CayenneDataObject;

import park.model.Customer;

/**
 * Class _Person was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Person extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String NAME_PROPERTY = "name";
    public static final String P_TYPE_PROPERTY = "pType";
    public static final String VERSION_PROPERTY = "version";
    public static final String TO_CUSTOMER_PROPERTY = "toCustomer";

    public static final String ID_PK_COLUMN = "ID";

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPType(String pType) {
        writeProperty("pType", pType);
    }
    public String getPType() {
        return (String)readProperty("pType");
    }

    public void setVersion(Integer version) {
        writeProperty("version", version);
    }
    public Integer getVersion() {
        return (Integer)readProperty("version");
    }

    public void setToCustomer(Customer toCustomer) {
        setToOneTarget("toCustomer", toCustomer, true);
    }

    public Customer getToCustomer() {
        return (Customer)readProperty("toCustomer");
    }


}
