package park.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import park.model.Customer;
import park.model.PriceTable;
import park.model.Stay;
import park.model.VehicleType;

/**
 * Class _Vehicle was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Vehicle extends CayenneDataObject {

    public static final String COLOR_PROPERTY = "color";
    public static final String LICENSE_PLATE_PROPERTY = "licensePlate";
    public static final String CUSTOMER_PROPERTY = "customer";
    public static final String PRICE_TABLE_PROPERTY = "priceTable";
    public static final String STAYS_PROPERTY = "stays";
    public static final String TO_VEHICLE_TYPE_PROPERTY = "toVehicleType";

    public static final String LICENSE_PLATE_PK_COLUMN = "LICENSE_PLATE";

    public void setColor(String color) {
        writeProperty("color", color);
    }
    public String getColor() {
        return (String)readProperty("color");
    }

    public void setLicensePlate(String licensePlate) {
        writeProperty("licensePlate", licensePlate);
    }
    public String getLicensePlate() {
        return (String)readProperty("licensePlate");
    }

    public void setCustomer(Customer customer) {
        setToOneTarget("customer", customer, true);
    }

    public Customer getCustomer() {
        return (Customer)readProperty("customer");
    }


    public void setPriceTable(PriceTable priceTable) {
        setToOneTarget("priceTable", priceTable, true);
    }

    public PriceTable getPriceTable() {
        return (PriceTable)readProperty("priceTable");
    }


    public void addToStays(Stay obj) {
        addToManyTarget("stays", obj, true);
    }
    public void removeFromStays(Stay obj) {
        removeToManyTarget("stays", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Stay> getStays() {
        return (List<Stay>)readProperty("stays");
    }


    public void setToVehicleType(VehicleType toVehicleType) {
        setToOneTarget("toVehicleType", toVehicleType, true);
    }

    public VehicleType getToVehicleType() {
        return (VehicleType)readProperty("toVehicleType");
    }


}
