--geral_nacionalidade
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	1	 ,'	Afeganistão	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	2	 ,'	África do Sul	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	3	 ,'	Albânia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	4	 ,'	Alemanha	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	5	 ,'	Alto Volta	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	6	 ,'	Andorra	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	7	 ,'	Angola	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	8	 ,'	Anguilla	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	9	 ,'	Antártica	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	10	 ,'	Antígua	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	11	 ,'	Antilhas Holandesas	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	12	 ,'	Arábia Saudita	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	13	 ,'	Argelia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	14	 ,'	Argentina	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	15	 ,'	Aruba	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	16	 ,'	Austrália	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	17	 ,'	Áustria	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	18	 ,'	Bahamas	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	19	 ,'	Bangladesh	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	20	 ,'	Barbados	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	21	 ,'	Barein	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	22	 ,'	Bélgica	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	23	 ,'	Belize	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	24	 ,'	Bênin	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	25	 ,'	Bermudas	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	26	 ,'	Birmânia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	27	 ,'	Bolívia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	28	 ,'	Botsuana	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	29	 ,'	Brasil	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	30	 ,'	Brunei	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	31	 ,'	Bulgária	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	32	 ,'	Burkina Faso	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	33	 ,'	Burundi	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	34	 ,'	Butão	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	35	 ,'	Cabo Verde	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	36	 ,'	Camarões	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	37	 ,'	Camboja	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	38	 ,'	Canadá	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	39	 ,'	Catar	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	40	 ,'	Ceuta e Melilla	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	41	 ,'	Chade	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	42	 ,'	Chile	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	43	 ,'	Chipre	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	44	 ,'	Cingapura	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	45	 ,'	Colômbia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	46	 ,'	Congo	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	47	 ,'	Coréia do Norte	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	48	 ,'	Coréia do Sul	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	49	 ,'	Costa do Marfim	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	50	 ,'	Costa Rica	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	51	 ,'	Croácia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	52	 ,'	Cuba	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	53	 ,'	Dinamarca	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	54	 ,'	Djibouti	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	55	 ,'	Dominica	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	56	 ,'	Egito	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	57	 ,'	El Salvador	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	58	 ,'	Emirados Árabes	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	59	 ,'	Equador	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	60	 ,'	Escócia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	61	 ,'	Espanha	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	62	 ,'	Estados Unidos da América	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	63	 ,'	Estônia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	64	 ,'	Etiópia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	65	 ,'	Filipinas	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	66	 ,'	Finlândia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	67	 ,'	Formosa	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	68	 ,'	França	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	69	 ,'	Gabão	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	70	 ,'	Gâmbia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	71	 ,'	Gana	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	72	 ,'	Gibraltar	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	73	 ,'	Granada	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	74	 ,'	Grécia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	75	 ,'	Groenlândia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	76	 ,'	Guadalupe	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	77	 ,'	Guan	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	78	 ,'	Guatemala	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	79	 ,'	Guiana	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	80	 ,'	Guiana Francesa	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	81	 ,'	Guiné	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	82	 ,'	Guiné-Bissau	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	83	 ,'	Guiné-Equatorial	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	84	 ,'	Haiti	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	85	 ,'	Holanda	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	86	 ,'	Honduras	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	87	 ,'	Hong Kong	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	88	 ,'	Hungria	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	89	 ,'	Iêmen	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	90	 ,'	Iêmen do Sul	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	91	 ,'	Ilha de Man	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	92	 ,'	Ilha de Pitcairn	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	93	 ,'	Ilha Jonhston	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	94	 ,'	Ilha Norfolk	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	95	 ,'	Ilha Wake	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	96	 ,'	Ilhas Cayman	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	97	 ,'	Ilhas Christmas	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	98	 ,'	Ilhas Coco (Keeling)	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	99	 ,'	Ilhas Comores	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	100	 ,'	Ilhas Coor	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	101	 ,'	Ilhas do Canal	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	102	 ,'	Ilhas Fiji	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	103	 ,'	Ilhas Maurício	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	104	 ,'	Ilhas Salomão	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	105	 ,'	Ilhas Seychelles	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	106	 ,'	Índia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	107	 ,'	Indonésia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	108	 ,'	Inglaterra	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	109	 ,'	Irã	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	110	 ,'	Iraque	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	111	 ,'	Irlanda	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	112	 ,'	Irlanda do Norte	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	113	 ,'	Islândia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	114	 ,'	Israel	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	115	 ,'	Itália	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	116	 ,'	Iugoslávia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	117	 ,'	Jamaica	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	118	 ,'	Japão	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	119	 ,'	Jordânia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	120	 ,'	kaweit	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	121	 ,'	Kiribati	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	122	 ,'	Laos	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	123	 ,'	Lesoto	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	124	 ,'	Líbano	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	125	 ,'	Libéria	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	126	 ,'	Líbia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	127	 ,'	Liechtenstein	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	128	 ,'	Luxemburgo	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	129	 ,'	Madagascar	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	130	 ,'	Malásia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	131	 ,'	Malavi	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	132	 ,'	Maldivas	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	133	 ,'	Mali	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	134	 ,'	Malta	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	135	 ,'	Marrocos	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	136	 ,'	Mauritânia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	137	 ,'	México	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	138	 ,'	Moçambique	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	139	 ,'	Mônaco	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	140	 ,'	Mongólia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	141	 ,'	Nauru	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	142	 ,'	Nepal	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	143	 ,'	Nicarágua	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	144	 ,'	Níger	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	145	 ,'	Nigéria	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	146	 ,'	Noruega	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	147	 ,'	Nova Zelândia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	148	 ,'	Omã	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	149	 ,'	País de Gales	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	150	 ,'	Panamá	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	151	 ,'	Papua Nova Guiné	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	152	 ,'	Paquistão	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	153	 ,'	Paraguai	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	154	 ,'	Peru	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	155	 ,'	Polônia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	156	 ,'	Porto Rico	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	157	 ,'	Portugal	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	158	 ,'	Qatar	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	159	 ,'	Quênia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	160	 ,'	República Centro-Africana	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	161	 ,'	República da Eslováquia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	162	 ,'	República Dominicana	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	163	 ,'	República Popular da China	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	164	 ,'	República Tcheca	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	165	 ,'	Rodésia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	166	 ,'	Romênia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	167	 ,'	Ruanda	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	168	 ,'	Rússia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	169	 ,'	Samoa Ocidental	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	170	 ,'	San Marino	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	171	 ,'	Santa Lúcia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	172	 ,'	São Cristóvão e Neves	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	173	 ,'	São Tomé e Príncipe	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	174	 ,'	São Vicente e Granadinas	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	175	 ,'	Senegal	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	176	 ,'	Serra Leoa	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	177	 ,'	Síria	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	178	 ,'	Somália	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	179	 ,'	Sri Lanka	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	180	 ,'	Suazilândia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	181	 ,'	Sudão	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	182	 ,'	Suécia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	183	 ,'	Suíça	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	184	 ,'	Suriname	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	185	 ,'	Tailândia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	186	 ,'	Tanzânia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	187	 ,'	Togo	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	188	 ,'	Tonga	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	189	 ,'	Trinidad e Tobago	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	190	 ,'	Tunísia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	191	 ,'	Turquia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	192	 ,'	Tuvalu	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	193	 ,'	Uganda	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	194	 ,'	União Soviética	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	195	 ,'	Uruguai	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	196	 ,'	Vanuatu	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	197	 ,'	Vaticano	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	198	 ,'	Venezuela	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	199	 ,'	Vietnã	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	200	 ,'	Zaire	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	201	 ,'	Zâmbia	 ');
insert into geral_nacionalidade(cdnacionalidade, dcnacionalidade)values(	202	 ,'	Zimbábue 	 ');
