package park.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import park.model.NaturalPerson;
import park.model.Parking;
import park.model.Stay;

/**
 * Class _Employee was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Employee extends CayenneDataObject {

    public static final String DT_ADMISSION_PROPERTY = "dtAdmission";
    public static final String NATURAL_PERSON_PROPERTY = "naturalPerson";
    public static final String PARKING_PROPERTY = "parking";
    public static final String STAYS_ENTRANCE_PROPERTY = "staysEntrance";
    public static final String STAYSOUTGOING_PROPERTY = "staysoutgoing";

    public static final String PERSON_ID_PK_COLUMN = "PERSON_ID";

    public void setDtAdmission(Date dtAdmission) {
        writeProperty("dtAdmission", dtAdmission);
    }
    public Date getDtAdmission() {
        return (Date)readProperty("dtAdmission");
    }

    public void setNaturalPerson(NaturalPerson naturalPerson) {
        setToOneTarget("naturalPerson", naturalPerson, true);
    }

    public NaturalPerson getNaturalPerson() {
        return (NaturalPerson)readProperty("naturalPerson");
    }


    public void setParking(Parking parking) {
        setToOneTarget("parking", parking, true);
    }

    public Parking getParking() {
        return (Parking)readProperty("parking");
    }


    public void addToStaysEntrance(Stay obj) {
        addToManyTarget("staysEntrance", obj, true);
    }
    public void removeFromStaysEntrance(Stay obj) {
        removeToManyTarget("staysEntrance", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Stay> getStaysEntrance() {
        return (List<Stay>)readProperty("staysEntrance");
    }


    public void addToStaysoutgoing(Stay obj) {
        addToManyTarget("staysoutgoing", obj, true);
    }
    public void removeFromStaysoutgoing(Stay obj) {
        removeToManyTarget("staysoutgoing", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Stay> getStaysoutgoing() {
        return (List<Stay>)readProperty("staysoutgoing");
    }


}
