package com.google.constructor.extras.security.cayenne.domain.auto;

import org.apache.cayenne.CayenneDataObject;

import com.google.constructor.extras.security.cayenne.domain.Role;
import com.google.constructor.extras.security.cayenne.domain.User;

/**
 * Class _UserRole was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UserRole extends CayenneDataObject {

    public static final String ROLE_ID_PROPERTY = "roleId";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String ROLE_PROPERTY = "role";
    public static final String USER_PROPERTY = "user";

    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";
    public static final String USER_ID_PK_COLUMN = "USER_ID";

    public void setRoleId(Long roleId) {
        writeProperty("roleId", roleId);
    }
    public Long getRoleId() {
        return (Long)readProperty("roleId");
    }

    public void setUserId(Long userId) {
        writeProperty("userId", userId);
    }
    public Long getUserId() {
        return (Long)readProperty("userId");
    }

    public void setRole(Role role) {
        setToOneTarget("role", role, true);
    }

    public Role getRole() {
        return (Role)readProperty("role");
    }


    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


}
