package park.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import park.model.Person;
import park.model.Vehicle;

/**
 * Class _Customer was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Customer extends CayenneDataObject {

    public static final String PAYMENT_DAY_PROPERTY = "paymentDay";
    public static final String PERSON_PROPERTY = "person";
    public static final String VEHICLES_PROPERTY = "vehicles";

    public static final String PERSON_ID_PK_COLUMN = "PERSON_ID";

    public void setPaymentDay(Integer paymentDay) {
        writeProperty(PAYMENT_DAY_PROPERTY, paymentDay);
    }
    public Integer getPaymentDay() {
        return (Integer)readProperty(PAYMENT_DAY_PROPERTY);
    }

    public void setPerson(Person person) {
        setToOneTarget(PERSON_PROPERTY, person, true);
    }

    public Person getPerson() {
        return (Person)readProperty(PERSON_PROPERTY);
    }


    public void addToVehicles(Vehicle obj) {
        addToManyTarget(VEHICLES_PROPERTY, obj, true);
    }
    public void removeFromVehicles(Vehicle obj) {
        removeToManyTarget(VEHICLES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Vehicle> getVehicles() {
        return (List<Vehicle>)readProperty(VEHICLES_PROPERTY);
    }


}
