package park.model.auto;

import java.util.List;

import org.apache.cayenne.ObjectContext;
import org.apache.cayenne.query.NamedQuery;

import park.model.Vehicle;

/**
 * This class was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _DataMap {

    public static final String VEHICLE_FIND_BY_LICENSE_PLATE_QUERYNAME = "Vehicle.findByLicensePlate";

    public static final String VEHICLE_FIND_BY_LICENSE_PLATE_EJBQL_QUERYNAME = "Vehicle.findByLicensePlateEJBQL";

    public static final String VEHICLE_TYPE_FIND_BY_VEHICLE_TYPE_QUERYNAME = "VehicleType.findByVehicleType";

    public List<Vehicle> performVehicle_findByLicensePlate(ObjectContext context , String licensePlate) {
        String[] parameters = {
            "licensePlate",
        };

        Object[] values = {
            licensePlate,
        };

        return context.performQuery(new NamedQuery("Vehicle.findByLicensePlate", parameters, values));
    }
}