package park.model.auto;



/**
 * This class was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _DataMap {

    public static final String VEHICLE_FIND_BY_LICENSE_PLATE_QUERYNAME = "Vehicle.findByLicensePlate";

    public static final String VEHICLE_TYPE_FIND_BY_VEHICLE_TYPE_QUERYNAME = "VehicleType.findByVehicleType";
}