package park.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import park.model.NaturalPerson;
import park.model.Parking;
import park.model.Stay;

/**
 * Class _Employee was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Employee extends CayenneDataObject {

    public static final String DT_ADMISSION_PROPERTY = "dtAdmission";
    public static final String ENTRANCE_STAYS_PROPERTY = "entranceStays";
    public static final String NATURAL_PERSON_PROPERTY = "naturalPerson";
    public static final String OUTGOING_STAYS_PROPERTY = "outgoingStays";
    public static final String PARKING_PROPERTY = "parking";

    public static final String NATURAL_PERSON_ID_PK_COLUMN = "NATURAL_PERSON_ID";

    public void setDtAdmission(Date dtAdmission) {
        writeProperty(DT_ADMISSION_PROPERTY, dtAdmission);
    }
    public Date getDtAdmission() {
        return (Date)readProperty(DT_ADMISSION_PROPERTY);
    }

    public void addToEntranceStays(Stay obj) {
        addToManyTarget(ENTRANCE_STAYS_PROPERTY, obj, true);
    }
    public void removeFromEntranceStays(Stay obj) {
        removeToManyTarget(ENTRANCE_STAYS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Stay> getEntranceStays() {
        return (List<Stay>)readProperty(ENTRANCE_STAYS_PROPERTY);
    }



    public NaturalPerson getNaturalPerson() {
        return (NaturalPerson)readProperty(NATURAL_PERSON_PROPERTY);
    }


    public void addToOutgoingStays(Stay obj) {
        addToManyTarget(OUTGOING_STAYS_PROPERTY, obj, true);
    }
    public void removeFromOutgoingStays(Stay obj) {
        removeToManyTarget(OUTGOING_STAYS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Stay> getOutgoingStays() {
        return (List<Stay>)readProperty(OUTGOING_STAYS_PROPERTY);
    }


    public void setParking(Parking parking) {
        setToOneTarget(PARKING_PROPERTY, parking, true);
    }

    public Parking getParking() {
        return (Parking)readProperty(PARKING_PROPERTY);
    }


}
