package park.model.auto;

import java.util.Date;

import park.model.Customer;
import park.model.Person;

/**
 * Class _LegalEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LegalEntity extends Person {

    public static final String DT_FOUNDATION_PROPERTY = "dtFoundation";
    public static final String TAXPAYERS_ID_PROPERTY = "taxpayersId";
    public static final String CUSTOMER_PROPERTY = "customer";

    public static final String ID_PK_COLUMN = "ID";

    public void setDtFoundation(Date dtFoundation) {
        writeProperty(DT_FOUNDATION_PROPERTY, dtFoundation);
    }
    public Date getDtFoundation() {
        return (Date)readProperty(DT_FOUNDATION_PROPERTY);
    }

    public void setTaxpayersId(String taxpayersId) {
        writeProperty(TAXPAYERS_ID_PROPERTY, taxpayersId);
    }
    public String getTaxpayersId() {
        return (String)readProperty(TAXPAYERS_ID_PROPERTY);
    }

    public void setCustomer(Customer customer) {
        setToOneTarget(CUSTOMER_PROPERTY, customer, true);
    }

    public Customer getCustomer() {
        return (Customer)readProperty(CUSTOMER_PROPERTY);
    }


}
