package park.model.auto;

import org.apache.cayenne.CayenneDataObject;

import park.model.Customer;

/**
 * Class _Person was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Person extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String DISCRIMINATOR_PROPERTY = "discriminator";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String VERSION_PROPERTY = "version";
    public static final String CUSTOMER_PROPERTY = "customer";

    public static final String ID_PK_COLUMN = "ID";

    public void setAddress(String address) {
        writeProperty(ADDRESS_PROPERTY, address);
    }
    public String getAddress() {
        return (String)readProperty(ADDRESS_PROPERTY);
    }

    public void setDiscriminator(String discriminator) {
        writeProperty(DISCRIMINATOR_PROPERTY, discriminator);
    }
    public String getDiscriminator() {
        return (String)readProperty(DISCRIMINATOR_PROPERTY);
    }

    public void setId(Long id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Long getId() {
        return (Long)readProperty(ID_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setVersion(Integer version) {
        writeProperty(VERSION_PROPERTY, version);
    }
    public Integer getVersion() {
        return (Integer)readProperty(VERSION_PROPERTY);
    }

    public void setCustomer(Customer customer) {
        setToOneTarget(CUSTOMER_PROPERTY, customer, true);
    }

    public Customer getCustomer() {
        return (Customer)readProperty(CUSTOMER_PROPERTY);
    }


}
