package park.model.auto;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import park.model.Vehicle;

/**
 * Class _PriceTable was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PriceTable extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String ITEM_PROPERTY = "item";
    public static final String PRICE_PROPERTY = "price";
    public static final String VEHICLES_PROPERTY = "vehicles";

    public static final String ID_PK_COLUMN = "ID";

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setItem(String item) {
        writeProperty("item", item);
    }
    public String getItem() {
        return (String)readProperty("item");
    }

    public void setPrice(BigDecimal price) {
        writeProperty("price", price);
    }
    public BigDecimal getPrice() {
        return (BigDecimal)readProperty("price");
    }

    public void addToVehicles(Vehicle obj) {
        addToManyTarget("vehicles", obj, true);
    }
    public void removeFromVehicles(Vehicle obj) {
        removeToManyTarget("vehicles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Vehicle> getVehicles() {
        return (List<Vehicle>)readProperty("vehicles");
    }


}
