package park.model.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import park.model.Employee;
import park.model.Parking;
import park.model.Vehicle;

/**
 * Class _Stay was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Stay extends CayenneDataObject {

    public static final String DT_ENTRANCE_PROPERTY = "dtEntrance";
    public static final String DT_OUTGOING_PROPERTY = "dtOutgoing";
    public static final String HR_ENTRANCE_PROPERTY = "hrEntrance";
    public static final String HR_OUTGOING_PROPERTY = "hrOutgoing";
    public static final String ID_PROPERTY = "id";
    public static final String STATUS_PROPERTY = "status";
    public static final String TOTAL_PRICE_PROPERTY = "totalPrice";
    public static final String VERSION_PROPERTY = "version";
    public static final String EMPLOYEE_PROPERTY = "employee";
    public static final String EMPLOYEE1_PROPERTY = "employee1";
    public static final String PARKING_PROPERTY = "parking";
    public static final String VEHICLE_PROPERTY = "vehicle";

    public static final String ID_PK_COLUMN = "ID";

    public void setDtEntrance(Date dtEntrance) {
        writeProperty(DT_ENTRANCE_PROPERTY, dtEntrance);
    }
    public Date getDtEntrance() {
        return (Date)readProperty(DT_ENTRANCE_PROPERTY);
    }

    public void setDtOutgoing(Date dtOutgoing) {
        writeProperty(DT_OUTGOING_PROPERTY, dtOutgoing);
    }
    public Date getDtOutgoing() {
        return (Date)readProperty(DT_OUTGOING_PROPERTY);
    }

    public void setHrEntrance(Date hrEntrance) {
        writeProperty(HR_ENTRANCE_PROPERTY, hrEntrance);
    }
    public Date getHrEntrance() {
        return (Date)readProperty(HR_ENTRANCE_PROPERTY);
    }

    public void setHrOutgoing(Date hrOutgoing) {
        writeProperty(HR_OUTGOING_PROPERTY, hrOutgoing);
    }
    public Date getHrOutgoing() {
        return (Date)readProperty(HR_OUTGOING_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setStatus(String status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public String getStatus() {
        return (String)readProperty(STATUS_PROPERTY);
    }

    public void setTotalPrice(BigDecimal totalPrice) {
        writeProperty(TOTAL_PRICE_PROPERTY, totalPrice);
    }
    public BigDecimal getTotalPrice() {
        return (BigDecimal)readProperty(TOTAL_PRICE_PROPERTY);
    }

    public void setVersion(Integer version) {
        writeProperty(VERSION_PROPERTY, version);
    }
    public Integer getVersion() {
        return (Integer)readProperty(VERSION_PROPERTY);
    }

    public void setEmployee(Employee employee) {
        setToOneTarget(EMPLOYEE_PROPERTY, employee, true);
    }

    public Employee getEmployee() {
        return (Employee)readProperty(EMPLOYEE_PROPERTY);
    }


    public void setEmployee1(Employee employee1) {
        setToOneTarget(EMPLOYEE1_PROPERTY, employee1, true);
    }

    public Employee getEmployee1() {
        return (Employee)readProperty(EMPLOYEE1_PROPERTY);
    }


    public void setParking(Parking parking) {
        setToOneTarget(PARKING_PROPERTY, parking, true);
    }

    public Parking getParking() {
        return (Parking)readProperty(PARKING_PROPERTY);
    }


    public void setVehicle(Vehicle vehicle) {
        setToOneTarget(VEHICLE_PROPERTY, vehicle, true);
    }

    public Vehicle getVehicle() {
        return (Vehicle)readProperty(VEHICLE_PROPERTY);
    }


}
