package park.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import park.model.Customer;
import park.model.PriceTable;
import park.model.Stay;
import park.model.VehicleType;

/**
 * Class _Vehicle was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Vehicle extends CayenneDataObject {

    public static final String COLOR_PROPERTY = "color";
    public static final String LICENSE_PLATE_PROPERTY = "licensePlate";
    public static final String CUSTOMER_PROPERTY = "customer";
    public static final String PRICE_TABLE_PROPERTY = "priceTable";
    public static final String STAYS_PROPERTY = "stays";
    public static final String VEHICLE_TYPE_PROPERTY = "vehicleType";

    public static final String LICENSE_PLATE_PK_COLUMN = "LICENSE_PLATE";

    public void setColor(String color) {
        writeProperty(COLOR_PROPERTY, color);
    }
    public String getColor() {
        return (String)readProperty(COLOR_PROPERTY);
    }

    public void setLicensePlate(String licensePlate) {
        writeProperty(LICENSE_PLATE_PROPERTY, licensePlate);
    }
    public String getLicensePlate() {
        return (String)readProperty(LICENSE_PLATE_PROPERTY);
    }

    public void setCustomer(Customer customer) {
        setToOneTarget(CUSTOMER_PROPERTY, customer, true);
    }

    public Customer getCustomer() {
        return (Customer)readProperty(CUSTOMER_PROPERTY);
    }


    public void setPriceTable(PriceTable priceTable) {
        setToOneTarget(PRICE_TABLE_PROPERTY, priceTable, true);
    }

    public PriceTable getPriceTable() {
        return (PriceTable)readProperty(PRICE_TABLE_PROPERTY);
    }


    public void addToStays(Stay obj) {
        addToManyTarget(STAYS_PROPERTY, obj, true);
    }
    public void removeFromStays(Stay obj) {
        removeToManyTarget(STAYS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Stay> getStays() {
        return (List<Stay>)readProperty(STAYS_PROPERTY);
    }


    public void setVehicleType(VehicleType vehicleType) {
        setToOneTarget(VEHICLE_TYPE_PROPERTY, vehicleType, true);
    }

    public VehicleType getVehicleType() {
        return (VehicleType)readProperty(VEHICLE_TYPE_PROPERTY);
    }


}
