package park.model.auto;

import java.util.Date;

import park.model.Person;

/**
 * Class _LegalEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LegalEntity extends Person {

    public static final String DT_FOUNDATION_PROPERTY = "dtFoundation";
    public static final String TAXPAYERS_ID_PROPERTY = "taxpayersId";
    public static final String PERSON_PROPERTY = "person";

    public static final String PERSON_ID_PK_COLUMN = "PERSON_ID";

    public void setDtFoundation(Date dtFoundation) {
        writeProperty("dtFoundation", dtFoundation);
    }
    public Date getDtFoundation() {
        return (Date)readProperty("dtFoundation");
    }

    public void setTaxpayersId(String taxpayersId) {
        writeProperty("taxpayersId", taxpayersId);
    }
    public String getTaxpayersId() {
        return (String)readProperty("taxpayersId");
    }

    public void setPerson(Person person) {
        setToOneTarget("person", person, true);
    }

    public Person getPerson() {
        return (Person)readProperty("person");
    }


}
