CREATE TABLE SHIRO_USER_ROLE (USER_ID BIGINT NOT NULL, ROLE_ID BIGINT NOT NULL, PRIMARY KEY (USER_ID, ROLE_ID));
CREATE TABLE SHIRO_ROLE_PERMISSION (ROLE_ID BIGINT NOT NULL, PERMISSION VARCHAR(50) NOT NULL, PRIMARY KEY (ROLE_ID, PERMISSION));
CREATE TABLE SHIRO_USER (ID BIGINT NOT NULL, USERNAME VARCHAR(50) NOT NULL UNIQUE, EMAIL VARCHAR(100) NOT NULL UNIQUE, PASSWORD VARCHAR(50) NOT NULL, VERSION INTEGER, PRIMARY KEY (ID));
CREATE TABLE SHIRO_ROLE (ID BIGINT NOT NULL, DESCRIPTION VARCHAR(255), NAME VARCHAR(50) NOT NULL, PRIMARY KEY (ID));
ALTER TABLE SHIRO_ROLE_PERMISSION ADD CONSTRAINT FK_SHIRO_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SHIRO_ROLE (ID);
ALTER TABLE SHIRO_USER_ROLE ADD CONSTRAINT FK_SHIRO_USER_ROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES SHIRO_USER (ID);
ALTER TABLE SHIRO_USER_ROLE ADD CONSTRAINT FK_SHIRO_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SHIRO_ROLE (ID);
CREATE TABLE SHIRO_SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME));
INSERT INTO SHIRO_SEQUENCE (SEQ_NAME, SEQ_COUNT) VALUES ('SHIRO_USER_SEQ', 0);
INSERT INTO SHIRO_SEQUENCE (SEQ_NAME, SEQ_COUNT) VALUES ('SHIRO_ROLE_SEQ', 0);

/*For cayenne*/
CREATE TABLE AUTO_PK_SUPPORT (TABLE_NAME CHAR(100) NOT NULL,  NEXT_ID BIGINT NOT NULL,  PRIMARY KEY(TABLE_NAME));
DELETE FROM AUTO_PK_SUPPORT WHERE TABLE_NAME IN ('SHIRO_ROLE', 'SHIRO_ROLE_PERMISSION', 'SHIRO_USER', 'SHIRO_USER_ROLE');
INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('SHIRO_ROLE', 200);
INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('SHIRO_ROLE_PERMISSION', 200);
INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('SHIRO_USER', 200);
INSERT INTO AUTO_PK_SUPPORT (TABLE_NAME, NEXT_ID) VALUES ('SHIRO_USER_ROLE', 200);

